### ISSUE TITLE
minor week 8 inconsistencies

### ISSUE THREAD

**Issue by coltonoscopy** [cs50/docs#106]
Seems there are a few minor differences between the code shown in lecture the code shown in the notes for Week 8, pointed out by an online student:

- Lecture code for application.py with froshIMs seems to be a superset of the code shown in lecture, which may be okay in the interest of giving students *more* info rather than less, but an example is that there's a missing conditional for "captain" in the lecture code, whereas it shows up in notes.
- store.html seems to be omitted from the notes during the shopping cart section.

**Comment by dlloyd09** [comment]
@ummcheng mind updating and PRing?

**Comment by ummcheng** [comment]
#107
