### ISSUE TITLE
Some Latex formatting is missing ( caesar , vigenere)

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/docs#122]
In the caesar and vigenere problem docs, I see:

`\[c_i = (p_i + k_j) \bmod 26\]`

rather than a formatted version.

I also notice in my console that I get 
/extensions/MathMenu.js?V=2.7.1
Failed to load resource: the server responded with a status of 404 (Not Found)
/extensions/MathZoom.js?V=2.7.1 
Failed to load resource: the server responded with a status of 404

Not sure if that's related.

**Comment by dmalan** [comment]
Seems `MathJax.js`, which we're now embedding in the `.html` file tries to load additional files. Will figure out how best to embed all!

**Comment by curiouskiwi** [comment]
This was fixed at some point. closing...
