### ISSUE TITLE
Update edX submission instructions

### ISSUE THREAD

**Issue by brianyu28** [cs50/docs#127]
When we debut the new `check50` and integrate it with `CS50.me`, we'll need to...

For `pset6`, replace the `submit50` slug `cs50/2017/x/pset6` with:

- C-to-Python slugs:
  - `cs50/2017/x/python/mario/less`
  - `cs50/2017/x/python/mario/more`
  - `cs50/2017/x/python/greedy`
  - `cs50/2017/x/python/credit`
  - `cs50/2017/x/python/caesar`
  - `cs50/2017/x/python/vigenere`
  - `cs50/2017/x/python/crack`
- Sentiments slugs:
  - `cs50/2017/x/smile`
  - `cs50/2017/x/tweets`
  - `cs50/2017/x/sentiments`

For `pset0`, if we're going to have students submit via GitHub:

- instructions for creating a `cs50/2017/x/scratch` branch, and uploading their `.sb` file.

For all psets:

- mandate the `cs50/` prefix if we're going to get rid of the assumption of `cs50/` at the beginning

CC @dmalan @crossroads1112

**Comment by dmalan** [comment]
@brianyu28, closable now?

**Comment by brianyu28** [comment]
Yep!
