### ISSUE TITLE
Finance spec inconsistency w/ staff solution

### ISSUE THREAD

**Issue by annieechen** [cs50/docs#19]
"Also display the user’s current cash balance along with a grand total (i.e., stocks' total value plus cash)." under Index

![image](https://cloud.githubusercontent.com/assets/15977250/19834514/f319951c-9e38-11e6-9a54-0c6726bd75e4.png)
Staff solution doesn't have the grand total.

**Comment by dmalan** [comment]
Thanks, should be fixed momentarily!
