### ISSUE TITLE
AP on edX (links lead to 2016 docs with 2017 deadlines)

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/docs#196]
From the course page: https://courses.edx.org/courses/course-v1:HarvardX+CS50+AP/course/  the links for FAQs, Instructions, Progress, and Syllabus all refer to a 2017 deadline.  @Erin-c

**Comment by dlloyd09** [comment]
I think this may have been fixed a while back?

**Comment by curiouskiwi** [comment]
@dlloyd09 the link to the syllabus still goes to http://docs.cs50.net/2016/x/ap/references/syllabus/syllabus.html

**Comment by dlloyd09** [comment]
Okay, the link's been edited and a 2017 syllabus is being built and pushed
to docs!
