### ISSUE TITLE
[Credit problem] Mastercard has new range of numbers

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/docs#198]
MC has a new BIN range of 222100-272099 in addition to their existing 510000-549999 That will be a bit trickier! https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html 

Do we need to update the spec / solution / check  to handle this new range? Or, perhaps just say "you don't need to handle this range in this problem"?

**Comment by curiouskiwi** [comment]
@dmalan should we  update this?

**Comment by dlloyd09** [comment]
I think the new range is weird enough that we're better off just excluding it from consideration. Resolved by 3133b04.
