### ISSUE TITLE
whodunit... we no longer ask

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/docs#209]
>When submitting this problem, you’ll be asked whodunit!

Now that we've removed the step 2 form from the submission, we no longer ask whodunit.

Maybe we should add this to the README.md as the last question?  and tell them to come back and answer it once they've found out?

**Comment by curiouskiwi** [comment]
@dmalan was asked about this again today.

**Comment by dmalan** [comment]
Ack, sorry for missing this so long ago! https://github.com/cs50/docs/commit/14eb1437003abb01a34ea1de41420db08ddc78c3
