### ISSUE TITLE
Yahoo Finance API endpoint service was discontinued

### ISSUE THREAD

**Issue by antonalekseev** [cs50/docs#218]
Unfortunately, Yahoo Finance API endpoint `http://download.finance.yahoo.com/d/quotes.csv` mentioned in https://github.com/cs50/docs/blob/d874daaf91ac96fbc64ae3be39b6d7ce3a59591b/_pages/problems/finance/finance.adoc#background and used by `lookup()` function in `finance/helpers.py` of Problem Set 7 is no longer available. `download.finance.yahoo.com` doesn't even resolve. Here is [post](https://forums.yahoo.net/t5/Yahoo-Finance-help/http-download-finance-yahoo-com-d-quotes-csv-s-GOOG-amp-f/m-p/387662/highlight/true#M6207) by Yahoo support staff member which says:

> UPDATE:  It has come to our attention that this service is being used in violation of the Yahoo Terms of Service.  As such, the service is being discontinued.  For all future markets and equities data research, please refer to finance.yahoo.com.  Thank you.

**Comment by nathanhannig** [comment]
The docs should be updated to mention yahoo no longer works and that an alternative is being used in the code.

I got confused reading the directions because the page came back with error. 

https://docs.cs50.net/2018/x/psets/7/pset7.html

**Comment by dlloyd09** [comment]
The API for this problem set has been rewritten to use a different service, and the specification has been updated accordingly.

**Comment by dlloyd09** [comment]
See, e.g., 1e3081a
