### ISSUE TITLE
Make no longer gives the "<program> is up to date" message.  Specs need to be changed to reflect? 

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/docs#23]
In the Find problem, this paragraph no longer fully applies:

>The first line tells `make` that the "target" called `generate` should be built by invoking the second line’s command. Moreover, that first line tells make that `generate` is dependent on `generate.c`, the implication of which is that `make` will only re-build `generate` on subsequent runs if that file was modified since make last built `generate`. Neat time-saving trick, eh? In fact, go ahead and execute the command below again, assuming you haven’t modified `generate.c`.

     make generate

>You should be informed that `generate` is already up-to-date. 

(note that this also applies to the  `https://cdn.cs50.net/2016/x/psets/3/pset3/pset3.html` spec, and has raised questions from edX students).

**Comment by dmalan** [comment]
Ah, want to submit a PR? We actually tweaked `make` to forcibly recompile each time, just to avoid this confusion. (And to ward off corner cases where a `Makefile` doesn't mention some file as a dependency and thus doesn't get rebuilt when it changes.)

**Comment by curiouskiwi** [comment]
This is still generating questions.  Any update?

**Comment by kzidane** [comment]
Relevant: https://github.com/cs50/docs/pull/26#issuecomment-269898135

**Comment by dmalan** [comment]
Oops, sorry, looks like we were awaiting a PR. 0:-) Fixed!
