### ISSUE TITLE
RNG links to reference.cs50.net need slight fix

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/docs#24]
The 2 links to reference.cs50.net (in the Getting Ready) section currently show:

https://reference.cs50.net/stdlib.h/srand48  and
https://reference.cs50.net/stdlib.h/drand48

These should be:

https://reference.cs50.net/stdlib/srand48
https://reference.cs50.net/stdlib/drand48

(without the `.h` in the folder name)

From here:
http://docs.cs50.net/2016/x/ap/problems/rng/rng.html

(reported by a student)

**Comment by dmalan** [comment]
thanks!

**Comment by dmalan** [comment]
Thanks! Want to submit a PR?

**Comment by curiouskiwi** [comment]
Have done so.  Closing.
