### ISSUE TITLE
Confusing Flash instructions in Problem Set 0 

### ISSUE THREAD

**Issue by kimberleejohnson** [cs50/docs#340]
Hi there! I'm a new student, and when I went to follow the instructions to make sure Flash was enabled in Chrome, I got a bit confused. I think the instructions as they are in the problem set are a bit out of date: https://docs.cs50.net/2018/x/psets/0/pset0.html#tldr

Right now it reads: 
"Make sure that your web browser has Flash enabled. If you’re using Google Chrome, you can go to chrome://settings/content, click on Advanced → Content settings, and make sure you "allow" Flash!"

To make this more clear to future students with less experience (like me!) I'd suggest revising to: 
"Make sure that your web browser has Flash enabled. If you're using Google Chrome, _you can type chrome://settings/content in your browser, then scroll down to the "Flash" section. Make sure "Ask First" is enabled so you can allow Flash to run when you're using Scratch._"

Thank you! 
Kimberlee

**Comment by curiouskiwi** [comment]
Hi @kimberleejohnson, if you are just starting out, you'd be best to follow the current course (2019/x) as the 2018 is now outdated with regards to this Scratch problem.   In the past, Scratch was Flash-based but the latest version (v 3.0) is not.  It is this version that is currently being used for CS50x on edX.  Here's the latest spec: https://docs.cs50.net/2019/x/psets/0/index.html  which then links you to the Scratch spec: https://docs.cs50.net/2019/x/psets/0/scratch.html

**Comment by kimberleejohnson** [comment]
Thanks @curiouskiwi! As an FYI, I got to that outdated link because of a Google search [0], and it looks like the 2018 link is the first one that pops up. 

I'm not an SEO expert, but if there's a way to make the 2019 link show up first for other students (I'm sure I won't be the only one to feel, well, lazy on a Sunday night and click on the first link without noticing the date in the url), that might be worthwhile! 

[0] I had a hard time figuring out where the problem set was linked in EdX, but eventually realized what all the icons in the navbar meant. 

![Screen Shot 2019-06-09 at 7 32 57 PM](https://user-images.githubusercontent.com/28582074/59169067-79fcbe80-8aed-11e9-92b0-c0ca508cb14d.png)
