### ISSUE TITLE
Wrong information in What's new

### ISSUE THREAD

**Issue by Youssef1313** [cs50/docs#348]
https://docs.cs50.net/2019/x/new.html
Problem sets part is copied from what's new in 2018, but isn't valid in 2019.
music now isn't in 2019 psets.

**Comment by brianyu28** [comment]
Hi @Youssef1313, thanks for pointing this out! I've updated the docs to include the new problems for 2019.

**Comment by Youssef1313** [comment]
@brianyu28 , I think music also was removed in 2019, Shouldn't that be mentioned also ?
