### ISSUE TITLE
Typo in Lecture 4 notes

### ISSUE THREAD

**Issue by tommylenz** [cs50/docs#379]
In the [notes for lecture 4](https://cs50.harvard.edu/college/2020/spring/notes/4/#string) , chapter string, there is a typo in the second sub-item:

"But it turns out that each character is ~~in~~ stored in memory at a byte with some address, ..."

**Comment by tommylenz** [comment]
I can't find the notes file, and I'm not even sure whether this is the correct place to issue this, but if not feel free to forward it!

**Comment by curiouskiwi** [comment]
Thanks @tommylenz  I've made the correction.
