### ISSUE TITLE
In-correct method for <form> [CS50x 2021: WEEK-9 notes]

### ISSUE THREAD

**Issue by skyfall01** [cs50/docs#383]
Link to notes: https://cs50.harvard.edu/x/2021/notes/9/#post

In the POST method documentation, the method used inside form tag is mentioned as "form". There is no such method for form tag.

During lecture(video), Prof. Malan used `<form action="/greet" method="post">`  for demonstrating usage of POST method

![form](https://user-images.githubusercontent.com/33621393/111944302-56a5d680-8afd-11eb-84fc-9aa8e0025a10.jpg)

**Comment by curiouskiwi** [comment]
thanks.  Will fix.
