### ISSUE TITLE
There's a mistake in Problem Set 2 page

### ISSUE THREAD

**Issue by newshahn** [cs50/docs#387]
In the advice section in [pset2](https://cs50.harvard.edu/x/2021/psets/2/), there's a sentence going like this:

> For instance, if trying to compile hello, and
> `make readability`
> is yielding errors, try running
> `help50 make readability`
> instead!

The word "hello" on the first line should be changed to "readability".

**Comment by dmalan** [comment]
Ah, thanks, fixed!
