### ISSUE TITLE
Wrong API URL in CS50 Finance

### ISSUE THREAD

**Issue by TenType** [cs50/docs#394]
In the [CS50 Finance problem](https://cs50.harvard.edu/x/2022/psets/9/finance/#background), following the API URL example with a valid API key leads to an error:
> Indeed, IEX lets you download stock quotes via their API (application programming interface) using URLs like `https://cloud-sse.iexapis.com/stable/stock/nflx/quote?token=API_KEY`.

Looking at the documentation on IEX, the SSE endpoint is [only available for paid users](https://iexcloud.io/docs/api/#sse-streaming). I believe the correct URL should be `https://cloud.iexapis.com/stable/stock/nflx/quote?token=API_KEY` (`cloud-sse` -> `cloud`), which is used in the problem distribution code.

**Comment by rongxin-liu** [comment]
Thanks for bringing this to our attention.

[https://github.com/cs50/harvard/commit/16d2df48239b96c0aa055ef24ac1a58b03c3e252](https://github.com/cs50/harvard/commit/16d2df48239b96c0aa055ef24ac1a58b03c3e252)
