### ISSUE TITLE
Can't submit extra files as needed

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/docs#53]
re: SPELLER problem:

> You may add functions to dictionary.c or to files of your own creation so long as all of your code compiles via make.

If a student does create these files and creates their own Makefile, they might figure out that `check50` can still run by including those extra files as part of the command line args.  But, `submit50` does not allow them to submit any additional files, so the grading will fail. 

Files that will be submitted:
 Makefile
 dictionary.c
 dictionary.h
 questions.txt
 speller.c

Should we be advising students not to use extra files instead?

**Comment by dlloyd09** [comment]
Good question. In the past it was OK, but the new check50 when it rolls out is going to be more strict about this. Should we preemptively prohibit this @dmalan? Could we have students include a `files.txt` which is a list of all .C and .H files essential for their program to run, if they write more?

**Comment by dlloyd09** [comment]
Closing this issue; I've submitted a PR to relax this restriction for now; will let you know if this merges in. Will need to consult with @brianyu28 and @dmalan.

**Comment by dlloyd09** [comment]
All set, @curiouskiwi !
