### ISSUE TITLE
change AP docs to use `default` layout

### ISSUE THREAD

**Issue by dmalan** [cs50/docs#6]
A la `problems/*`. This new layout:
- Embeds YouTube vids responsively so that they resize for mobile.
- Adds support for LaTeX, a la https://github.com/cs50/docs/blame/master/problems/caesar/caesar.adoc#L45.

https://github.com/cs50/docs/blob/master/_layouts/default.html

Aok to make your own for AP too, but I suspect I'll continue tweaking `default` for a few weeks if you want to wait a bit!

**Comment by dmalan** [comment]
@Erin-c mind tackling?

**Comment by Erin-c** [comment]
@dmalan done 👍
