### ISSUE TITLE
Students assume 50 jpgs and hard-code their loops which then fail check50

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/docs#72]
The spec explicitly says

> But you should ultimately find that the image contains 50 JPEGs.

This leads many students to assume they should hard-code their number of jpgs to 50 and structure their program this way (with a for loop that ends when 50 jpgs are found).  This works perfectly fine with the card.raw that is in the distro code, but `check50` uses a different raw file (with only 16 files) so their program is then "killed by server" because it never finds the 17th signature and goes into an infinite loop.

Should we  add something like:  

>Note that your program may be tested with a different card image so you should not hard-code that number, but instead, search the entire file for all the JPEGs within it.

**Comment by dlloyd09** [comment]
Sure, we can do this. Let me think of how best to phrase a note for the Hints section.
